# Generated by Django 5.1.4 on 2026-04-13 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('missa', 'Missa'), ('colacao', 'Colação de Grau'), ('almoco', 'Almoço / Festa')], max_length=20, unique=True, verbose_name='Tipo')),
                ('nome_local', models.CharField(max_length=200, verbose_name='Nome do local')),
                ('endereco', models.TextField(verbose_name='Endereço completo')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('link_maps', models.URLField(blank=True, verbose_name='Link Google Maps')),
                ('ativo', models.BooleanField(default=True, verbose_name='Exibir no site')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='FotoConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do remetente')),
                ('relacionamento', models.CharField(blank=True, max_length=120, verbose_name='Relação com a Micaelle')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('imagem', models.ImageField(upload_to='convidados/', verbose_name='Foto')),
                ('aprovada', models.BooleanField(default=False, verbose_name='Aprovada (publicar na galeria)')),
                ('enviada_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Foto enviada por convidado',
                'verbose_name_plural': 'Fotos enviadas por convidados',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda (opcional)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('destaque', models.BooleanField(default=False, verbose_name='Foto destaque (maior)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Exibir na galeria')),
                ('adicionada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto da galeria',
                'verbose_name_plural': 'Fotos da galeria',
                'ordering': ['ordem', '-adicionada_em'],
            },
        ),
        migrations.CreateModel(
            name='TextoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('hero_titulo', 'Hero — Título principal'), ('hero_subtitulo', 'Hero — Subtítulo (curso/universidade)'), ('historia_titulo', 'História — Título da seção'), ('historia_corpo', 'História — Texto principal'), ('agradecimento_frase', 'Agradecimento — Frase/citação'), ('agradecimento_homenageados', 'Agradecimento — Homenageados (um por linha)'), ('envio_descricao', 'Envio de fotos — Descrição')], max_length=60, unique=True, verbose_name='Seção')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texto do site',
                'verbose_name_plural': 'Textos do site',
                'ordering': ['secao'],
            },
        ),
    ]
